import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');

test('showcase interior design node is registered in frontend and permissions', () => {
  assert.match(read('src/types/canvas.ts'), /\| 'showcase-interior-design'/);
  assert.match(read('src/config/nodeRegistry.ts'), /type: 'showcase-interior-design'/);
  assert.match(read('src/components/Canvas.tsx'), /ShowcaseInteriorDesignNode/);
  assert.match(read('src/components/Canvas.tsx'), /'showcase-interior-design': ShowcaseInteriorDesignNode/);
  assert.match(read('src/components/Canvas.tsx'), /showcaseStyle/);
  assert.match(read('src/components/Canvas.tsx'), /widthMm: 1200/);
  assert.match(read('src/components/Canvas.tsx'), /baseHeightMm: 300/);
  assert.match(read('src/components/Canvas.tsx'), /glassHeightMm: 1400/);
  assert.match(read('src/components/Canvas.tsx'), /capHeightMm: 180/);
  assert.match(read('src/components/Canvas.tsx'), /hasCap: false/);
  assert.match(read('src/components/Canvas.tsx'), /emptyExhibitMode: 'empty'/);
  assert.match(read('src/components/Canvas.tsx'), /emptyExhibitQuery: ''/);
  assert.match(read('src/components/Canvas.tsx'), /layoutMode: 'manual'/);
  assert.match(read('src/components/Canvas.tsx'), /manualLayoutItems: \[\]/);
  assert.match(read('src/components/Canvas.tsx'), /manualLayoutReferenceImage: ''/);
  assert.match(read('src/components/Canvas.tsx'), /perspectiveEnabled: true/);
  assert.match(read('src/components/Canvas.tsx'), /explodedViewEnabled: false/);
  assert.match(read('src/config/portTypes.ts'), /'showcase-interior-design': \{ inputs: \['image'\], outputs: \['image'\] \}/);
  assert.match(read('src/utils/nodePlacement.ts'), /'showcase-interior-design': \{ w: 520, h: 680 \}/);
  assert.match(read('src/components/NodeActionBar.tsx'), /'showcase-interior-design'/);
  assert.match(read('backend/src/auth/toolPermissions.js'), /'showcase-interior-design'/);
});

test('showcase interior design component wires shared controls and generation services', () => {
  const source = read('src/components/nodes/ShowcaseInteriorDesignNode.tsx');
  assert.match(source, /id="color-material-reference"/);
  assert.match(source, /ColorMaterialPresetSelect/);
  assert.match(source, /buildShowcaseInteriorDesignPrompt/);
  assert.match(source, /previewReferenceImages = useMemo\(\(\) => \[/);
  assert.match(source, /runtimeReferenceImages = \[/);
  assert.match(source, /\.\.\.\(layoutMode === 'manual' \? \[d\.manualLayoutReferenceImage\] : exhibitItems\.map\(\(item\) => item\.url\)\)/);
  assert.doesNotMatch(source, /buildShowcaseInteriorScaleReferenceDataUrl/);
  assert.doesNotMatch(source, /buildScaledExhibitReferenceImage/);
  assert.doesNotMatch(source, /imageDataUrlToPngDataUrl/);
  assert.doesNotMatch(source, /scaleReferenceImage/);
  assert.match(source, /generateExternalImage/);
  assert.match(source, /submitImageAsync/);
  assert.match(source, /queryImageStatus/);
  assert.match(source, /queryExternalImageStatus/);
  assert.match(source, /exhibitItems/);
  assert.match(source, /heightMm/);
  assert.match(source, /高度 mm/);
  assert.match(source, /layoutMode/);
  assert.match(source, /emptyExhibitMode/);
  assert.match(source, /emptyExhibitQuery/);
  assert.match(source, /自动搜索相关展品/);
  assert.match(source, /空展柜/);
  assert.match(source, /输入展品主题/);
  assert.match(source, /manualLayoutItems/);
  assert.match(source, /manualLayoutReferenceImage/);
  assert.match(source, /ShowcaseManualLayoutModal/);
  assert.match(source, /buildManualLayoutReferenceImage/);
  assert.match(source, /draftItemsRef/);
  assert.match(source, /setDraftItemsState/);
  assert.match(source, /commitDraftItems/);
  assert.match(source, /window\.addEventListener\('pointerup', endDrag/);
  assert.match(source, /手动排版模式/);
  assert.match(source, /mode === 'auto'/);
  assert.match(source, /自动尺寸模式暂不可用/);
  assert.match(source, /disabled=\{isReadonly \|\| busy \|\| mode === 'auto'\}/);
  assert.match(source, /setManualLayoutOpen\(true\)/);
  assert.match(source, /排版/);
  assert.match(source, /layoutMode === 'manual'[\s\S]*manualLayoutReferenceImage/);
  assert.match(source, /\.\.\.\(layoutMode === 'manual' \? \[manualLayoutReferenceImage\] : exhibitItems\.map\(\(item\) => item\.url\)\)/);
  assert.match(source, /verticalGuideLines/);
  assert.match(source, /horizontalGuideLines/);
  assert.match(source, /viewBox=\{`0 0 \$\{widthMm\} \$\{heightMm\}`\}/);
  assert.match(source, /x \+= 100/);
  assert.match(source, /y \+= 100/);
  assert.doesNotMatch(source, /ctx\.fillText\(`手动布局参考图/);
  assert.doesNotMatch(source, /ctx\.strokeRect\(x, y, w, h\)/);
  assert.doesNotMatch(source, /const grid = 100/);
  assert.doesNotMatch(source, /backgroundSize: `\$\{\(100 \/ widthMm\) \* 100\}%/);
  assert.match(source, /function ratioValue/);
  assert.match(source, /function closestAspectRatio/);
  assert.match(source, /showcaseStyle\.widthMm \/ totalHeightMm/);
  assert.match(source, /aspectRatioSource/);
  assert.match(source, /按展柜宽高自动匹配/);
  assert.match(source, /perspectiveEnabled/);
  assert.match(source, /透视效果/);
  assert.match(source, /dimensionMarksEnabled/);
  assert.match(source, /explodedViewEnabled/);
});
