import type { JobVisualStyle } from './jobOptions'
import catalogJson from './visualStyleCatalog.json'

export type VisualStyleCategory =
  | 'auto'
  | 'corporate'
  | 'editorial'
  | 'expressive'
  | 'hand-drawn'
  | 'specialty'

export const VISUAL_STYLE_CATEGORY_LABELS: Record<VisualStyleCategory, string> = {
  auto: '智能推荐',
  corporate: '企业 / 产品',
  editorial: '编辑 / 出版',
  expressive: '表现 / 印刷',
  'hand-drawn': '手绘 / 笔墨',
  specialty: '特色',
}

export interface VisualStyleTrait {
  label: string
  text: string
}

export interface VisualStylePreviewSlides {
  cover: string
  content: string
  closing: string
}

export interface VisualStyleCatalogEntry {
  id: JobVisualStyle
  category: VisualStyleCategory
  title: string
  tagline: string
  character: string
  bestFor: string[]
  notFor: string
  traits: VisualStyleTrait[]
  pairedRendering: string | null
  colorHint: string | null
  rules: string[]
  exampleProjectId: string | null
  exampleFolder: string | null
  previewSlides: VisualStylePreviewSlides | null
  collageStyles?: JobVisualStyle[]
}

const catalog = catalogJson as { version: number; styles: VisualStyleCatalogEntry[] }

export const VISUAL_STYLE_CATALOG: VisualStyleCatalogEntry[] = catalog.styles

export const VISUAL_STYLE_CATALOG_MAP: Record<JobVisualStyle, VisualStyleCatalogEntry> =
  Object.fromEntries(
    VISUAL_STYLE_CATALOG.map((entry) => [entry.id, entry]),
  ) as Record<JobVisualStyle, VisualStyleCatalogEntry>

export type PreviewSlideKind = 'cover' | 'content' | 'closing'

/** Bump when re-running export_visual_style_previews.py so browsers pick up new assets. */
export const VISUAL_STYLE_PREVIEW_VERSION = catalog.version

/** Public URL for a rasterized preview (generated by scripts/export_visual_style_previews.py). */
export function visualStylePreviewUrl(
  styleId: JobVisualStyle,
  kind: PreviewSlideKind,
): string {
  return `/assets/visual-styles/${styleId}/${kind}.webp?v=${VISUAL_STYLE_PREVIEW_VERSION}`
}

export function visualStyleCollageUrl(): string {
  return `/assets/visual-styles/auto/collage.webp?v=${VISUAL_STYLE_PREVIEW_VERSION}`
}

export function exampleProjectOnlineUrl(exampleProjectId: string | null): string | null {
  if (!exampleProjectId) return null
  return `https://hugohe3.github.io/ppt-master/?project=${exampleProjectId}`
}

export function catalogEntryFor(styleId: JobVisualStyle): VisualStyleCatalogEntry {
  return VISUAL_STYLE_CATALOG_MAP[styleId]
}

export function listGalleryStyles(showAuto: boolean): VisualStyleCatalogEntry[] {
  return VISUAL_STYLE_CATALOG.filter((e) => showAuto || e.id !== 'auto')
}

/** Group gallery entries by category (auto first if included). */
export function listGalleryStyleGroups(showAuto: boolean): {
  category: VisualStyleCategory
  label: string
  entries: VisualStyleCatalogEntry[]
}[] {
  const entries = listGalleryStyles(showAuto)
  const order: VisualStyleCategory[] = [
    'auto',
    'corporate',
    'editorial',
    'expressive',
    'hand-drawn',
    'specialty',
  ]
  return order
    .map((category) => ({
      category,
      label: VISUAL_STYLE_CATEGORY_LABELS[category],
      entries: entries.filter((e) => e.category === category),
    }))
    .filter((g) => g.entries.length > 0)
}
